import {TYPES,STATUSES,STAGES,money,sum,cents,decimal,today,allocate,status,outstanding,rejected,waitingDays,validate,totalsWarnings,partialShare} from './domain.js?v=1.9';
import * as store from './data.js?v=1.16';
import {buildWorkbook} from './xlsx.js?v=1.13';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={dashboard:'M3 3h7v7H3z M14 3h7v4h-7z M14 11h7v10h-7z M3 14h7v7H3z',cases:'M3 7h18v14H3z M7 7V3h10v4 M3 12h18',credits:'M4 3h16v18l-4-2-4 2-4-2-4 2z M8 8h8 M8 12h8',companies:'M4 21V3h12v18 M16 9h4v12 M8 7h4 M8 11h4 M8 15h4 M2 21h20',reports:'M4 20V10 M10 20V4 M16 20v-7 M22 20H2'};
const icon=k=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[k]||icons.cases}"/></svg>`;
const nav=[['dashboard','Dashboard'],['cases','Περιστατικά'],['credits','Πιστωτικά'],['companies','Εταιρείες'],['reports','Αναφορές']];
let data={cases:[],companies:[]},page='dashboard',filters={},draft=null,dirty=false,saving=false,reportBy='doctor',calendarMonth=new Date();
const company=id=>data.companies.find(c=>c.id===id)?.name||'Άγνωστη εταιρεία';
const badge=s=>`<span class="badge ${s==='Ολοκληρωμένο'||s==='Παραλήφθηκε'?'green':s==='Κλειστό με διαφορά'||s==='Απορρίφθηκε'?'red':s==='Αναμονή πιστωτικών'||s==='Ζητήθηκε'?'amber':'blue'}">${esc(s)}</span>`;
const date=s=>s?new Date(s+'T12:00:00').toLocaleDateString('el-GR'):'—';
const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('el-GR');
function filtered(){return data.cases.filter(c=>{const q=normalize(filters.q||''),incident=c.incidentDate||c.date;return (!q||normalize([c.code,c.patient,c.doctor,...c.lines.map(l=>company(l.companyId))].join(' ')).includes(q))&&(!filters.doctor||c.doctor===filters.doctor)&&(!filters.company||c.lines.some(l=>l.companyId===filters.company))&&(!filters.status||status(c)===filters.status)&&(!filters.type||c.type===filters.type)&&(!filters.from||incident>=filters.from)&&(!filters.to||incident<=filters.to);});}
function lineRows(cases){return cases.flatMap(c=>c.lines.filter(l=>!filters.company||l.companyId===filters.company).map(l=>({c,l})));}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),5000);}
function options(values,selected,all='Όλα'){return (all===null?'':`<option value="">${all}</option>`)+values.map(v=>{const [key,label]=Array.isArray(v)?v:[v,v];return `<option value="${esc(key)}" ${key===selected?'selected':''}>${esc(label)}</option>`;}).join('');}
const iso=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
const rangeModes=['Y','M','D','-'];
const rangeDate=value=>value?value.split('-').reverse().join('/'):'';
const rangeLabel=()=>filters.rangeMode==='-'||!filters.from?'Όλες οι ημερ.':filters.rangeMode==='D'?rangeDate(filters.from):`${rangeDate(filters.from)} - ${rangeDate(filters.to)}`;
function setRangeMode(mode,anchor=filters.rangeAnchor||filters.from||today()){filters.rangeMode=mode;if(mode==='-'){delete filters.from;delete filters.to;return;}filters.rangeAnchor=anchor;const d=new Date(anchor+'T12:00:00');if(mode==='Y'){filters.from=`${d.getFullYear()}-01-01`;filters.to=`${d.getFullYear()}-12-31`;}else if(mode==='M'){filters.from=iso(new Date(d.getFullYear(),d.getMonth(),1));filters.to=iso(new Date(d.getFullYear(),d.getMonth()+1,0));}else{filters.from=iso(d);filters.to=iso(d);}}
function filterBar(){filters.rangeMode||=filters.from&&filters.to?'D':'-';if(filters.from)calendarMonth=new Date(filters.from+'T12:00:00');const inactive=filters.rangeMode==='-';return `<div class="filters"><label class="search">Αναζήτηση<input id="search" placeholder="Κωδικός, ασθενής, ιατρός, εταιρεία…" value="${esc(filters.q||'')}"></label><label>Ιατρός<select data-filter="doctor">${options([...new Set(data.cases.map(c=>c.doctor))].sort(),filters.doctor,'Όλοι οι ιατροί')}</select></label><label>Εταιρεία<select data-filter="company">${options(data.companies.map(c=>[c.id,c.name]),filters.company,'Όλες οι εταιρείες')}</select></label><label>Κατάσταση<select data-filter="status">${options(STATUSES,filters.status,'Όλες οι καταστάσεις')}</select></label><label>Τύπος<select data-filter="type">${options(TYPES,filters.type,'Όλοι οι τύποι')}</select></label><div class="date-range-wrap"><span class="filter-label">Ημερομηνία περιστατικού</span><div class="date-range-control"><button type="button" id="range-mode" class="range-mode" title="Y: έτος · M: μήνας · D: ημέρα · −: όλες" aria-label="Τύπος περιόδου: ${filters.rangeMode}">${filters.rangeMode}</button><button type="button" id="range-prev" aria-label="Προηγούμενο διάστημα" ${inactive?'disabled':''}>◀</button><details id="range-picker"><summary id="range-open"><b>${rangeLabel()}</b><span class="calendar-caret">⌄</span></summary><div id="range-popover" class="range-popover">${calendarHTML()}</div></details><button type="button" id="range-next" aria-label="Επόμενο διάστημα" ${inactive?'disabled':''}>▶</button><button type="button" id="range-clear" aria-label="Όλες οι ημερομηνίες">×</button></div></div><button class="text-button" id="clear-filters">Καθαρισμός όλων</button></div>`;}
function companyFilterBar(){return `<div class="filters company-filters"><label class="search">Αναζήτηση<input id="search" placeholder="Εταιρεία, υπεύθυνος ή email…" value="${esc(filters.q||'')}"></label>${filters.q?'<button class="text-button" id="clear-filters">Καθαρισμός</button>':''}</div>`;}
function calendarHTML(){const year=calendarMonth.getFullYear(),month=calendarMonth.getMonth(),first=new Date(year,month,1),start=new Date(year,month,1-((first.getDay()+6)%7)),names=['Ιανουάριος','Φεβρουάριος','Μάρτιος','Απρίλιος','Μάιος','Ιούνιος','Ιούλιος','Αύγουστος','Σεπτέμβριος','Οκτώβριος','Νοέμβριος','Δεκέμβριος'];let days='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const value=iso(d),outside=d.getMonth()!==month,inRange=filters.from&&filters.to&&value>=filters.from&&value<=filters.to;days+=`<button type="button" data-day="${value}" class="${outside?'outside ':''}${value===filters.from||value===filters.to?'selected ':''}${inRange?'in-range':''}" aria-label="${date(value)}">${d.getDate()}</button>`;}return `<div class="calendar-head"><button type="button" id="month-prev" aria-label="Προηγούμενος μήνας">◀</button><b>${names[month]} ${year}</b><button type="button" id="month-next" aria-label="Επόμενος μήνας">▶</button></div><div class="weekdays"><span>Δ</span><span>Τ</span><span>Τ</span><span>Π</span><span>Π</span><span>Σ</span><span>Κ</span></div><div class="calendar-days">${days}</div><div class="calendar-help">Επιλέξτε αρχή και τέλος περιόδου</div>`;}
function renderCalendar(){const pop=$('#range-popover');if(!pop)return;pop.innerHTML=calendarHTML();$('#month-prev').onclick=()=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()-1,1);renderCalendar();};$('#month-next').onclick=()=>{calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+1,1);renderCalendar();};pop.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{if(filters.rangeMode==='-')filters.rangeMode='D';setRangeMode(filters.rangeMode,b.dataset.day);$('#range-picker').open=false;render();});}
function shiftRange(direction){if(!filters.from||filters.rangeMode==='-')return;const d=new Date(filters.from+'T12:00:00');if(filters.rangeMode==='Y')d.setFullYear(d.getFullYear()+direction);else if(filters.rangeMode==='M')d.setMonth(d.getMonth()+direction);else d.setDate(d.getDate()+direction);setRangeMode(filters.rangeMode,iso(d));render();}
function metrics(cases){const rows=lineRows(cases),target=sum(rows,x=>x.c.closedReason?0:outstanding(x.l)),received=sum(rows,x=>x.l.received),rejectedTotal=sum(rows,x=>rejected(x.l));return {target,received,rejected:rejectedTotal};}
function card(label,value,sub,cls=''){return `<div class="metric ${cls}"><span>${label}</span><strong>${value}</strong><small>${sub}</small></div>`;}
function empty(text='Δεν βρέθηκαν καταχωρίσεις.'){return `<div class="empty">${icon('cases')}<h3>${text}</h3><p>Προσθέστε ένα περιστατικό ή αλλάξτε τα φίλτρα.</p></div>`;}
function caseTable(cases){return cases.length?`<div class="table-wrap"><table><thead><tr><th>Περιστατικό / ασθενής</th><th>Ιατρός</th><th>Ημ. περιστατικού</th><th>Ημ. επιτροπής</th><th>Τύπος</th><th class="num">Κόστος υλικών</th><th class="num">Προς κάλυψη</th><th>Κατάσταση</th><th></th></tr></thead><tbody>${[...cases].sort((a,b)=>(b.incidentDate||b.date).localeCompare(a.incidentDate||a.date)).map(c=>`<tr><td><button class="link" data-case="${c.id}">${esc(c.code)}</button><small>${esc(c.patient)}</small></td><td>${esc(c.doctor)}</td><td>${date(c.incidentDate||c.date)}</td><td>${date(c.date)}</td><td>${esc(c.type)}</td><td class="num">${money(c.total)}</td><td class="num">${money(c.total-c.recognized)}</td><td>${badge(status(c))}</td><td><button class="edit-button" data-case="${c.id}" aria-label="Επεξεργασία ${esc(c.code)}">✎ Επεξεργασία</button></td></tr>`).join('')}</tbody></table></div>`:empty();}
function creditTable(rows){return rows.length?`<div class="table-wrap"><table class="credit-table"><thead><tr><th>Εταιρεία / περιστατικό</th><th>Κατάσταση</th><th class="num">Πρόταση</th><th class="num">Ζητήθηκε</th><th class="num">Παραλήφθηκε</th><th class="num">Εκκρεμεί</th><th>Αίτημα</th><th>Αναμονή</th></tr></thead><tbody>${[...rows].sort((a,b)=>waitingDays(b.l)-waitingDays(a.l)).map(({c,l})=>`<tr><td><button class="link" data-case="${c.id}">${esc(company(l.companyId))}</button><small>${esc(c.code)} · ${esc(c.patient)}</small></td><td>${badge(l.stage)}${c.closedReason?'<small>Κλειστό με διαφορά</small>':''}</td><td class="num">${!l.proposed&&l.requested?'—':money(l.proposed)}</td><td class="num">${l.stage==='Προς αίτηση'?'—':money(l.requested)}</td><td class="num">${money(l.received)}</td><td class="num strong">${c.closedReason?'—':money(outstanding(l))}</td><td>${date(l.requestDate)}</td><td>${l.stage==='Ζητήθηκε'?`<span class="days ${waitingDays(l)>30?'late':''}">${waitingDays(l)} ημέρες</span>`:'—'}</td></tr>`).join('')}</tbody></table></div>`:empty('Δεν υπάρχουν πιστωτικά σε αυτή την επιλογή.');}
function dashboard(cases){const m=metrics(cases);return `<div class="metrics metrics-3">${card('Πιστωτικά προς ανάκτηση',money(m.target),'ζητηθέντα ή προς αίτηση, μείον παραλαβές','accent')}${card('Παραληφθέντα',money(m.received),'ποσά που έχουν παραληφθεί','success')}${card('Απορριφθέντα',money(m.rejected),'αιτήματα που δεν θα ανακτηθούν','rejected')}</div><section class="panel"><div class="panel-title"><div><h2>Εκκρεμή πιστωτικά</h2><p>Προτεραιότητα στις μεγαλύτερες καθυστερήσεις</p></div><button id="all-credits" class="secondary">Όλα τα πιστωτικά ↗</button></div>${creditTable(lineRows(cases).filter(x=>!x.c.closedReason&&outstanding(x.l)>0))}</section><section class="panel"><div class="panel-title"><h2>Πρόσφατα περιστατικά</h2></div>${caseTable([...cases].sort((a,b)=>(b.incidentDate||b.date).localeCompare(a.incidentDate||a.date)).slice(0,5))}</section>`;}
function reports(cases){const groups=new Map();for(const {c,l} of lineRows(cases)){const key=reportBy==='doctor'?c.doctor:l.companyId;if(!groups.has(key))groups.set(key,{key,name:reportBy==='doctor'?key:company(key),cases:new Set(),cost:0,proposed:0,requested:0,received:0,rejected:0,pending:0});const g=groups.get(key);g.cases.add(c.id);g.cost+=l.cost;g.proposed+=l.proposed;g.requested+=l.stage==='Προς αίτηση'?0:l.requested;g.received+=l.received;g.rejected+=rejected(l);g.pending+=c.closedReason?0:outstanding(l);}return `<section class="panel"><div class="panel-title reports-title"><div><h2>${reportBy==='doctor'?'Εικόνα ανά ιατρό':'Εικόνα ανά εταιρεία'}</h2><p>Επιλέξτε όνομα για τα σχετικά περιστατικά</p></div><div class="report-tabs"><button data-report="doctor" class="${reportBy==='doctor'?'primary':'secondary'}">Ανά ιατρό</button><button data-report="company" class="${reportBy==='company'?'primary':'secondary'}">Ανά εταιρεία</button><button class="secondary" id="export">Εξαγωγή Excel</button></div></div>${groups.size?`<div class="table-wrap"><table><thead><tr><th>Όνομα</th><th>Περιστατικά</th><th class="num">Κόστος</th><th class="num">Προς κάλυψη</th><th class="num">Ζητήθηκε</th><th class="num">Παραλήφθηκε</th><th class="num">Απορρίφθηκε</th><th class="num">Εκκρεμεί</th></tr></thead><tbody>${[...groups.values()].sort((a,b)=>b.pending-a.pending).map(g=>`<tr><td><button class="link" data-drill="${esc(g.key)}">${esc(g.name)}</button></td><td>${g.cases.size}</td>${['cost','proposed','requested','received','rejected','pending'].map(k=>`<td class="num ${k==='rejected'&&g[k]?'rejected-amount':''}">${money(g[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty()}</section>`;}
function companiesView(){const q=normalize(filters.q||''),companies=data.companies.filter(c=>!q||normalize([c.name,c.contact,c.email,c.notes].join(' ')).includes(q));return `<section class="panel"><div class="panel-title"><h2>${companies.length} ${companies.length===1?'εταιρεία':'εταιρείες'}</h2></div>${companies.length?`<div class="table-wrap"><table><thead><tr><th>Εταιρεία</th><th>Υπεύθυνος</th><th>Email</th><th>Περιστατικά</th><th>Σημειώσεις</th><th></th></tr></thead><tbody>${companies.sort((a,b)=>a.name.localeCompare(b.name,'el')).map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.contact)||'—'}</td><td>${esc(c.email)||'—'}</td><td>${data.cases.filter(x=>x.lines.some(l=>l.companyId===c.id)).length}</td><td class="company-notes">${esc(c.notes)||'—'}</td><td><button class="secondary" data-company="${c.id}">Επεξεργασία</button></td></tr>`).join('')}</tbody></table></div>`:empty(q?'Δεν βρέθηκαν εταιρείες.':'Δεν έχουν καταχωριστεί εταιρείες.')}</section>`;}
function render(){const title=nav.find(x=>x[0]===page)[1];$('#app').innerHTML=`<aside><div class="brand"><span class="brand-mark">m<span>c</span></span><div>MediCredit<small>MEDITERRANEO HOSPITAL</small></div></div><div class="nav-label">ΤΜΗΜΑ ΠΡΟΜΗΘΕΙΩΝ</div><nav>${nav.map(([key,label])=>`<button data-nav="${key}" class="${page===key?'active':''}">${icon(key)}${label}${key==='credits'?`<span class="nav-count">${data.cases.flatMap(c=>c.closedReason?[]:c.lines.filter(l=>outstanding(l)>0)).length}</span>`:''}</button>`).join('')}</nav><div class="sidebar-foot"><span class="online-dot"></span>Supabase · Ασφαλής σύνδεση<small>Υλικά · Επιτροπές · Πιστωτικά</small></div></aside><main><header><span>Mediterraneo <b>Hospital</b><span class="header-separator">/</span>Προμήθειες</span><div><button class="text-button" id="refresh">Ανανέωση</button><button class="text-button" id="logout">Αποσύνδεση</button></div></header><div class="workspace"><div class="page-heading"><div><div class="eyebrow">ΕΛΕΓΧΟΣ & ΑΝΑΚΤΗΣΗ ΠΙΣΤΩΤΙΚΩΝ</div><h1>${title}</h1><p>${page==='dashboard'?'Η εικόνα των επιτροπών, με μια ματιά.':page==='cases'?'Κάθε απόφαση, κάθε εταιρεία, σε ένα σημείο.':page==='credits'?'Από το αίτημα μέχρι την παραλαβή.':page==='companies'?'Το μητρώο των προμηθευτών σας.':'Ποσά και εκκρεμότητες με δυνατότητα ανάλυσης.'}</p></div><button class="primary" id="new">＋ ${page==='companies'?'Νέα εταιρεία':'Νέο περιστατικό'}</button></div>${page==='companies'?companyFilterBar():filterBar()}<div id="content"></div><footer>MediCredit v1.0 <span>Τμήμα Προμηθειών · Mediterraneo Hospital</span></footer></div></main>`;renderContent();bindShell();}
function renderContent(){const cases=filtered();$('#content').innerHTML=page==='dashboard'?dashboard(cases):page==='cases'?`<section class="panel"><div class="panel-title"><h2>${cases.length} ${cases.length===1?'περιστατικό':'περιστατικά'}</h2><button class="secondary" id="export">Εξαγωγή Excel</button></div>${caseTable(cases)}</section>`:page==='credits'?`<section class="panel"><div class="panel-title"><h2>Παρακολούθηση πιστωτικών</h2><button class="secondary" id="export">Εξαγωγή Excel</button></div>${creditTable(lineRows(cases))}</section>`:page==='companies'?companiesView():reports(cases);$('#content').querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>editCase(b.dataset.case));$('#content').querySelectorAll('[data-company]').forEach(b=>b.onclick=()=>editCompany(b.dataset.company));$('#content').querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{reportBy=b.dataset.report;renderContent();});$('#content').querySelectorAll('[data-drill]').forEach(b=>b.onclick=()=>{filters[reportBy]=b.dataset.drill;page='cases';render();});if($('#all-credits'))$('#all-credits').onclick=()=>{page='credits';render();};if($('#export'))$('#export').onclick=exportExcel;}
function bindShell(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{page=b.dataset.nav;render();});$('#new').onclick=()=>page==='companies'?editCompany():editCase();$('#refresh').onclick=()=>reload().catch(e=>toast(e.message));$('#logout').onclick=async()=>{await store.logout();data={cases:[],companies:[]};loginView();};if($('#search'))$('#search').oninput=e=>{filters.q=e.target.value;renderContent();};document.querySelectorAll('[data-filter]').forEach(e=>e.onchange=()=>{filters[e.dataset.filter]=e.value;renderContent();});if($('#range-picker')){renderCalendar();$('#range-mode').onclick=()=>{const next=rangeModes[(rangeModes.indexOf(filters.rangeMode)+1)%rangeModes.length];setRangeMode(next);render();};$('#range-prev').onclick=()=>shiftRange(-1);$('#range-next').onclick=()=>shiftRange(1);$('#range-clear').onclick=()=>{setRangeMode('-');render();};}if($('#clear-filters'))$('#clear-filters').onclick=()=>{filters={rangeMode:'-'};render();};}
const field=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const moneyField=(name,label,value,extra='')=>field(name,label,decimal(value),'text',`inputmode="decimal" ${extra}`);
function editCase(id){draft=id?structuredClone(data.cases.find(c=>c.id===id)):{id:crypto.randomUUID(),version:0,code:'',patient:'',doctor:'',incidentDate:today(),date:today(),type:'Plafond',total:0,recognized:0,notes:'',closedReason:'',decision:null,lines:[]};draft.incidentDate||=draft.date;dirty=false;showCase();$('#editor').showModal();}
function filePicker(name,label,current){return `<label>${label}<span class="file-picker"><input type="file" name="${name}" accept="application/pdf"><span data-file-name>${current?esc(current.name):'Επιλογή PDF'}</span></span></label>`;}
function newLine(companyId=''){return {id:crypto.randomUUID(),companyId,cost:0,proposed:0,requested:0,received:0,stage:'Προς αίτηση',requestDate:'',receiveDate:'',creditNumber:'',notes:'',credit:null};}
function lineForm(l,i){return `<section class="line-card" data-line="${l.id}"><div class="line-title"><h3>Εταιρεία ${i+1}</h3><button type="button" class="text-button danger" data-remove="${l.id}">Αφαίρεση</button></div><div class="form-grid"><label>Εταιρεία<div class="company-select"><select name="companyId" required>${options(data.companies.map(c=>[c.id,c.name]),l.companyId,'Επιλέξτε εταιρεία')}</select><button type="button" class="secondary" data-new-company>＋ Νέα</button></div></label>${moneyField('cost','Κόστος υλικών (€)',l.cost)}${moneyField('proposed','Προτεινόμενο πιστωτικό (€)',l.proposed,draft.type==='Plafond'||draft.type==='Συγκεκριμένα υλικά'?'readonly':'')}<label>Παρακολούθηση<select name="stage">${options(STAGES,l.stage,null)}</select></label>${moneyField('requested','Ποσό αιτήματος (€)',l.requested)}${field('requestDate','Ημερομηνία αιτήματος',l.requestDate,'date')}${moneyField('received','Ποσό παραλαβής (€)',l.received)}${field('receiveDate','Ημερομηνία παραλαβής',l.receiveDate,'date')}${field('creditNumber','Αριθμός πιστωτικού (προαιρετικό)',l.creditNumber)}${filePicker('creditUpload','PDF πιστωτικού (προαιρετικό, έως 10 MB)',l.credit)}${l.credit?`<button type="button" class="link file-link" data-file-line="${l.id}">${esc(l.credit.name)} ↗</button>`:''}<label class="span-2">Σημειώσεις εταιρείας<textarea name="lineNotes" rows="2">${esc(l.notes)}</textarea></label></div></section>`;}
function showCase(){const d=$('#editor');d.innerHTML=`<form id="case-form"><div class="dialog-head"><div><small>ΠΕΡΙΣΤΑΤΙΚΟ ΕΠΙΤΡΟΠΗΣ</small><h2>${draft.version?`Επεξεργασία · ${esc(draft.code)}`:'Νέο περιστατικό'}</h2></div><button type="button" class="secondary" id="close">Κλείσιμο ×</button></div><div class="dialog-body"><div class="form-grid">${field('code','Κωδικός νοσηλείας *',draft.code,'text','required maxlength="80"')}${field('patient','Ασθενής *',draft.patient,'text','required maxlength="200"')}${field('doctor','Ιατρός *',draft.doctor,'text','required maxlength="200"')}${field('incidentDate','Ημερομηνία περιστατικού *',draft.incidentDate,'date','required')}${field('date','Ημερομηνία επιτροπής *',draft.date,'date','required')}<label>Τύπος περικοπής<select name="type">${options(TYPES,draft.type,null)}</select></label>${filePicker('decisionUpload','PDF απόφασης (έως 10 MB)',draft.decision)}${draft.decision?`<button type="button" class="link file-link" id="decision-file">${esc(draft.decision.name)} ↗</button>`:''}${moneyField('total','Συνολικό κόστος υλικών (€)',draft.total)}${moneyField('recognized','Αναγνωρισμένο ποσό (€)',draft.recognized)}<label class="span-2">Γενικές σημειώσεις<textarea name="notes" rows="2">${esc(draft.notes)}</textarea></label></div><div class="calculation" id="calculation"></div><div class="section-heading"><div><h2>Εταιρείες & πιστωτικά</h2><p>Στα συγκεκριμένα υλικά το κόστος περνά αυτόματα ως ποσό αιτήματος.</p></div><button type="button" class="primary add-company-line">＋ Εταιρεία</button></div><div id="lines">${draft.lines.map(lineForm).join('')}</div><div class="lines-end"><button type="button" class="primary add-company-line">＋ Προσθήκη εταιρείας</button></div><details ${draft.closedReason?'open':''}><summary>Κλείσιμο με διαφορά</summary><p>Χρησιμοποιείται όταν σταματά η διεκδίκηση και παραμένει διαφορά. Για επαναφορά, αδειάστε την αιτιολογία.</p><label>Αιτιολογία κλεισίματος<textarea name="closedReason" rows="2">${esc(draft.closedReason)}</textarea></label></details><div id="form-errors" role="alert"></div></div><div class="dialog-foot"><span id="draft-status">${badge(status(draft))}</span><button class="primary" type="submit">Αποθήκευση αλλαγών</button></div></form>`;
 $('#close').onclick=closeEditor;d.oncancel=e=>{e.preventDefault();closeEditor();};$('#case-form').oninput=()=>{dirty=true;calculate();};$('#case-form').onchange=e=>{dirty=true;if(e.target.name==='type'){draft.type=e.target.value;d.querySelectorAll('[name="proposed"]').forEach(x=>x.readOnly=['Plafond','Συγκεκριμένα υλικά'].includes(draft.type));}calculate();};d.querySelectorAll('.add-company-line').forEach(b=>b.onclick=()=>{try{readDraft();draft.lines.push(newLine());appendLine();dirty=true;}catch(e){formError(e);}});
 bindLines();bindDatePaste();bindFileNames();if($('#decision-file'))$('#decision-file').onclick=()=>openFile(draft.decision);$('#case-form').onsubmit=saveDraft;calculate();}
function appendLine(){const i=draft.lines.length-1;$('#lines').insertAdjacentHTML('beforeend',lineForm(draft.lines[i],i));bindLines();bindDatePaste();bindFileNames();calculate();}
function parsePastedDate(value){const s=value.trim();let m;if(m=s.match(/^(\d{1,2})[\/.\-](\d{1,2})[\/.\-](\d{4})$/))return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;return '';}
function bindDatePaste(){$('#editor').querySelectorAll('input[type="date"]').forEach(input=>input.onpaste=e=>{const value=parsePastedDate(e.clipboardData.getData('text'));if(!value)return;e.preventDefault();input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));});}
function bindFileNames(){$('#editor').querySelectorAll('input[type="file"]').forEach(input=>input.onchange=()=>{const label=input.closest('.file-picker')?.querySelector('[data-file-name]');if(label)label.textContent=input.files[0]?.name||'Επιλογή PDF';});}
async function createCompanyInline(){try{readDraft();const name=prompt('Επωνυμία νέας εταιρείας:')?.trim();if(!name)return;if(data.companies.some(c=>normalize(c.name)===normalize(name)))throw Error('Η εταιρεία υπάρχει ήδη.');const c={id:crypto.randomUUID(),name,contact:'',email:'',notes:''};await store.saveCompany(c);data.companies.push(c);draft.lines.push(newLine(c.id));showCase();dirty=true;toast('Η εταιρεία δημιουργήθηκε και προστέθηκε στο περιστατικό.');}catch(e){formError(e);}}
function bindLines(){$('#editor').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{try{readDraft();const line=draft.lines.find(l=>l.id===b.dataset.remove);if((line.requestDate||line.received)&&!confirm('Να αφαιρεθεί η εταιρεία και η παρακολούθηση πιστωτικού από το περιστατικό;'))return;draft.lines=draft.lines.filter(l=>l.id!==b.dataset.remove);b.closest('.line-card').remove();dirty=true;calculate();}catch(e){formError(e);}});$('#editor').querySelectorAll('[data-file-line]').forEach(b=>b.onclick=()=>openFile(draft.lines.find(l=>l.id===b.dataset.fileLine).credit));$('#editor').querySelectorAll('[data-new-company]').forEach(b=>b.onclick=createCompanyInline);$('#editor').querySelectorAll('[name="received"]').forEach(input=>input.onchange=()=>{const el=input.closest('[data-line]'),amount=cents(input.value);if(amount<=0)return;const request=el.querySelector('[name="requested"]');if(cents(request.value)<amount)request.value=decimal(amount);const requestDate=el.querySelector('[name="requestDate"]');if(!requestDate.value)requestDate.value=today()<draft.date?draft.date:today();const receiveDate=el.querySelector('[name="receiveDate"]');if(!receiveDate.value)receiveDate.value=today();const stage=el.querySelector('[name="stage"]');stage.value=amount>=cents(request.value)?'Παραλήφθηκε':'Ζητήθηκε';calculate();});}
function readDraft(){const f=$('#case-form');for(const k of ['code','patient','doctor','incidentDate','date','type','notes','closedReason'])draft[k]=f.elements[k].value.trim();draft.total=cents(f.elements.total.value);draft.recognized=cents(f.elements.recognized.value);for(const el of f.querySelectorAll('[data-line]')){const l=draft.lines.find(l=>l.id===el.dataset.line);for(const k of ['companyId','stage','requestDate','receiveDate','creditNumber'])l[k]=el.querySelector(`[name="${k}"]`).value.trim();for(const k of ['cost','proposed','requested','received'])l[k]=cents(el.querySelector(`[name="${k}"]`).value);l.notes=el.querySelector('[name="lineNotes"]').value.trim();}}
function autofill(){
 // Απλοποίηση: συμπλήρωση αυτόματα όσων προκύπτουν από τα υπόλοιπα (αίτημα, ημερομηνίες, παραληφθέν).
 for(const l of draft.lines){
  if(l.stage==='Προς αίτηση')continue;
  if(!l.requested)l.requested=l.received>0?l.received:l.proposed;
  if(l.requested<l.received)l.requested=l.received;
  if(l.stage==='Παραλήφθηκε'&&!l.received)l.received=l.requested;
  if(!l.requestDate)l.requestDate=today()<draft.date?draft.date:today();
  if(l.received>0&&!l.receiveDate)l.receiveDate=today()<l.requestDate?l.requestDate:today();
  const el=$(`[data-line="${l.id}"]`);if(!el)continue;
  for(const k of ['requested','received'])el.querySelector(`[name="${k}"]`).value=decimal(l[k]);
  for(const k of ['requestDate','receiveDate'])el.querySelector(`[name="${k}"]`).value=l[k];
 }
}
function calculate(){try{readDraft();const total=sum(draft.lines,l=>l.cost),target=draft.total-draft.recognized;if(target<0)throw Error('Το αναγνωρισμένο ποσό υπερβαίνει το κόστος.');if(draft.type==='Plafond'&&total<=draft.total){const amounts=total===draft.total?allocate(draft.lines.map(l=>l.cost),target):draft.lines.map(l=>Math.min(l.cost,partialShare(l.cost,target,draft.total)));draft.lines.forEach((l,i)=>{l.proposed=amounts[i];const el=$(`[data-line="${l.id}"]`);el.querySelector('[name="proposed"]').value=decimal(l.proposed);});}if(draft.type==='Συγκεκριμένα υλικά'){draft.lines.forEach(l=>{l.proposed=l.cost;l.requested=l.cost;const el=$(`[data-line="${l.id}"]`);el.querySelector('[name="proposed"]').value=decimal(l.cost);el.querySelector('[name="requested"]').value=decimal(l.cost);});}$('#calculation').innerHTML=`<div><small>ΠΡΟΣ ΚΑΛΥΨΗ</small><strong>${money(target)}</strong></div><div><small>${draft.type==='Plafond'?'ΚΟΙΝΗ ΕΚΠΤΩΣΗ':'ΠΟΣΟΣΤΟ ΠΕΡΙΚΟΠΗΣ'}</small><strong>${draft.total?(100*target/draft.total).toLocaleString('el-GR',{maximumFractionDigits:4}):'0'}%</strong></div><div><small>ΕΛΕΓΧΟΣ ΚΟΣΤΟΥΣ</small><b class="${total===draft.total?'ok':'danger'}">${money(total)} / ${money(draft.total)}</b><small>Προτάσεις: ${money(sum(draft.lines,l=>l.proposed))}</small></div>${draft.type==='Plafond'?'<button type="button" id="use-proposals" class="secondary">Πρόταση → ποσό αιτήματος</button>':''}`;if($('#use-proposals'))$('#use-proposals').onclick=()=>{draft.lines.forEach(l=>{if(l.stage==='Προς αίτηση')$(`[data-line="${l.id}"] [name="requested"]`).value=decimal(l.proposed);});dirty=true;calculate();};$('#draft-status').innerHTML=badge(status(draft));}catch(e){$('#calculation').textContent=e.message;}}
function formError(e){$('#form-errors').textContent=e.message;$('#form-errors').scrollIntoView({block:'nearest'});}
async function saveDraft(e){
 e.preventDefault();if(saving)return;
 const button=e.submitter;
 try{
  readDraft();autofill();const errors=validate(draft);
  if(data.cases.some(c=>c.id!==draft.id&&normalize(c.code)===normalize(draft.code)))errors.push('Υπάρχει ήδη περιστατικό με αυτόν τον κωδικό.');
  if(errors.length)throw Error(errors.join('\n'));
  saving=true;button.disabled=true;button.textContent='Αποθήκευση…';
  const f=$('#case-form');f.inert=true;
  if(f.elements.decisionUpload.files[0])draft.decision=await store.upload(f.elements.decisionUpload.files[0],draft.id);
  for(const el of f.querySelectorAll('[data-line]')){
   const file=el.querySelector('[name="creditUpload"]').files[0];
   if(file)draft.lines.find(l=>l.id===el.dataset.line).credit=await store.upload(file,draft.id);
  }
  const warn=totalsWarnings(draft);await store.saveCase(draft);dirty=false;$('#editor').close();await reload();toast(warn.length?'Αποθηκεύτηκε (ημιτελές): '+warn.join(' '):'Το περιστατικό αποθηκεύτηκε.');
 }catch(e){formError(e);}
 finally{saving=false;if($('#case-form'))$('#case-form').inert=false;button.disabled=false;button.textContent=draft?.version?'Αποθήκευση αλλαγών':'Αποθήκευση περιστατικού';}
}
function closeEditor(){if(saving)return;if(dirty&&!confirm('Υπάρχουν μη αποθηκευμένες αλλαγές. Να κλείσει η φόρμα;'))return;$('#editor').close();dirty=false;}
async function openFile(file){const win=window.open('about:blank','_blank');if(win)win.opener=null;try{const url=await store.fileURL(file);if(win)win.location=url;else toast('Επιτρέψτε τα αναδυόμενα παράθυρα για να ανοίξει το PDF.');if(url.startsWith('blob:'))setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){win?.close();toast(e.message);}}
function editCompany(id){const c=id?data.companies.find(c=>c.id===id):{id:crypto.randomUUID(),name:'',contact:'',email:'',notes:''};dirty=false;$('#editor').innerHTML=`<form id="company-form"><div class="dialog-head"><h2>${id?'Επεξεργασία εταιρείας':'Νέα εταιρεία'}</h2><button type="button" class="secondary" id="close">Κλείσιμο ×</button></div><div class="dialog-body"><div class="form-grid">${field('name','Επωνυμία *',c.name,'text','required maxlength="200"')}${field('contact','Υπεύθυνος επικοινωνίας',c.contact)}${field('email','Email',c.email,'email')}<label class="span-2">Σημειώσεις<textarea name="notes">${esc(c.notes)}</textarea></label></div><div id="form-errors" role="alert"></div></div><div class="dialog-foot"><button class="primary" type="submit">Αποθήκευση εταιρείας</button></div></form>`;$('#editor').showModal();$('#close').onclick=closeEditor;$('#editor').oncancel=e=>{e.preventDefault();closeEditor();};$('#company-form').oninput=()=>dirty=true;$('#company-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const d=Object.fromEntries(new FormData(e.target));if(data.companies.some(x=>x.id!==c.id&&normalize(x.name)===normalize(d.name.trim())))throw Error('Η εταιρεία υπάρχει ήδη.');await store.saveCompany({id:c.id,...d,name:d.name.trim()});dirty=false;$('#editor').close();await reload();toast('Η εταιρεία αποθηκεύτηκε.');}catch(e){formError(e);}finally{b.disabled=false;}};}
function exportExcel(){const rows=[['Κωδικός','Ασθενής','Ιατρός','Ημερομηνία περιστατικού','Ημερομηνία επιτροπής','Τύπος','Κατάσταση περιστατικού','Εταιρεία','Κόστος EUR','Πρόταση EUR','Αίτημα EUR','Παραλαβή EUR','Απορριφθέν EUR','Εκκρεμές EUR','Κατάσταση πιστωτικού','Ημ. αιτήματος','Ημ. παραλαβής','Αριθμός πιστωτικού'],...lineRows(filtered()).map(({c,l})=>[c.code,c.patient,c.doctor,c.incidentDate||c.date,c.date,c.type,status(c),company(l.companyId),l.cost/100,l.proposed/100,l.stage==='Προς αίτηση'?'':l.requested/100,l.received/100,rejected(l)/100,c.closedReason?'':outstanding(l)/100,l.stage,l.requestDate,l.receiveDate,l.creditNumber])];const bytes=buildWorkbook(rows,{currencyColumns:[8,9,10,11,12,13]});const url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download='medicredit-'+today()+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function reload(){data=await store.load();render();}
function loginView(){$('#app').innerHTML=`<div class="login"><div class="brand"><span class="brand-mark">mc</span><div>MediCredit<small>MEDITERRANEO HOSPITAL</small></div></div><h1>Καλώς ήρθατε</h1><p>Σύνδεση Τμήματος Προμηθειών</p><form id="login">${field('email','Email','','email','required autocomplete="username"')}${field('password','Κωδικός πρόσβασης','','password','required autocomplete="current-password"')}<p id="login-error" role="alert"></p><button class="primary">Σύνδεση</button></form></div>`;$('#login').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await store.login(e.target.email.value,e.target.password.value);await reload();}catch(err){$('#login-error').textContent=err.message;e.submitter.disabled=false;}};}
function passwordResetView(){$('#app').innerHTML=`<div class="login"><div class="brand"><span class="brand-mark">mc</span><div>MediCredit<small>MEDITERRANEO HOSPITAL</small></div></div><h1>Νέος κωδικός</h1><p>Ορίστε τον νέο κωδικό σύνδεσης.</p><form id="password-reset">${field('password','Νέος κωδικός','','password','required minlength="8" autocomplete="new-password"')}${field('confirm','Επιβεβαίωση κωδικού','','password','required minlength="8" autocomplete="new-password"')}<p id="login-error" role="alert"></p><button class="primary">Αλλαγή κωδικού</button></form></div>`;$('#password-reset').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{if(e.target.password.value!==e.target.confirm.value)throw Error('Οι δύο κωδικοί δεν ταιριάζουν.');await store.updatePassword(e.target.password.value);await reload();toast('Ο κωδικός άλλαξε επιτυχώς.');}catch(err){$('#login-error').textContent=err.message;b.disabled=false;}};}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
if(store.recovering())passwordResetView();else if(store.signedIn())reload().catch(e=>{loginView();$('#login-error').textContent=e.message;});else loginView();



