import {config} from '../config.js';
import {validate,today,allocate} from './domain.js';
export const demo=config.mode==='demo';
let session=JSON.parse(sessionStorage.getItem('medicredit-session')||'null'),refreshing;
const base=config.supabaseUrl.replace(/\/$/,'');
async function auth(path,body){const r=await fetch(base+'/auth/v1/'+path,{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.msg||d.error_description||d.message||'Αποτυχία σύνδεσης.');session={...d,expires_at:Date.now()+d.expires_in*1000};sessionStorage.setItem('medicredit-session',JSON.stringify(session));return d;}
async function token(){if(!session)throw Error('Απαιτείται σύνδεση.');if(Date.now()>session.expires_at-60000){refreshing??=auth('token?grant_type=refresh_token',{refresh_token:session.refresh_token}).finally(()=>refreshing=null);await refreshing;}return session.access_token;}
async function api(path,{method='GET',body,headers={}}={}){const r=await fetch(base+path,{method,headers:{apikey:config.publishableKey,Authorization:'Bearer '+await token(),...(body instanceof Blob?{}:{'Content-Type':'application/json'}),...headers},body:body===undefined?undefined:body instanceof Blob?body:JSON.stringify(body)});if(!r.ok){let d;try{d=await r.json();}catch{}throw Error(d?.message||d?.msg||d?.error||`Αποτυχία (${r.status}). Ελέγξτε σύνδεση και δικαιώματα.`);}const text=await r.text();return text?JSON.parse(text):null;}
const dbp=demo?new Promise((resolve,reject)=>{const r=indexedDB.open('medicredit-demo-v1',1);r.onupgradeneeded=()=>{for(const name of ['cases','companies','files'])r.result.createObjectStore(name,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}):null;
async function local(store,mode,fn){const db=await dbp;return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode),req=fn(tx.objectStore(store));let result;req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Η αποθήκευση ακυρώθηκε.'));});}
async function allRemote(table){let rows=[],page;const fields=table==='mc_cases'?'id,payload,version':'*';do{page=await api(`/rest/v1/${table}?select=${fields}&order=id&limit=500&offset=${rows.length}`);rows.push(...page);}while(page.length===500);return rows;}
export const signedIn=()=>demo||!!session;
export async function login(email,password){if(!base||!config.publishableKey)throw Error('Συμπληρώστε το config.js για το νέο Supabase project.');await auth('token?grant_type=password',{email,password});}
export async function logout(){try{if(!demo)await api('/auth/v1/logout',{method:'POST'});}finally{session=null;sessionStorage.removeItem('medicredit-session');}}
const normalizeCase=c=>({...c,incidentDate:c.incidentDate||c.date});
export async function load(){if(demo)return {cases:(await local('cases','readonly',s=>s.getAll())).map(normalizeCase),companies:await local('companies','readonly',s=>s.getAll())};const members=await api('/rest/v1/mc_members?select=user_id&active=eq.true');if(!members.length)throw Error('Ο λογαριασμός δεν έχει ενεργή πρόσβαση στο Τμήμα Προμηθειών. Επικοινωνήστε με τον διαχειριστή.');const [rows,companies]=await Promise.all([allRemote('mc_cases'),allRemote('mc_companies')]);return {cases:rows.map(r=>normalizeCase({...r.payload,id:r.id,version:r.version})),companies};}
export async function saveCase(c){const errors=validate(c);if(errors.length)throw Error(errors.join('\n'));if(demo){const db=await dbp;return new Promise((resolve,reject)=>{const tx=db.transaction('cases','readwrite'),store=tx.objectStore('cases'),r=store.get(c.id);let saved;r.onsuccess=()=>{if((r.result?.version||0)!==(c.version||0)){tx.abort();return;}saved={...c,version:(c.version||0)+1};store.put(saved);};tx.oncomplete=()=>resolve(saved);tx.onabort=()=>reject(Error('Το περιστατικό άλλαξε σε άλλη καρτέλα. Κλείστε και ανανεώστε πριν την επεξεργασία.'));tx.onerror=()=>reject(tx.error);});}const row=await api('/rest/v1/rpc/mc_save_case',{method:'POST',body:{p_case:c,p_version:c.version||0}});return {...row.payload,id:row.id,version:row.version};}
export async function saveCompany(c){if(!c.name.trim())throw Error('Απαιτείται επωνυμία.');if(demo){await local('companies','readwrite',s=>s.put(c));return;}const body={id:c.id,name:c.name,contact:c.contact,email:c.email,notes:c.notes};await api('/rest/v1/mc_companies?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body});}
export async function upload(file,caseId){if(file.size>10*1024*1024)throw Error('Το PDF πρέπει να είναι έως 10 MB.');if(new TextDecoder().decode(await file.slice(0,5).arrayBuffer())!=='%PDF-')throw Error('Το αρχείο δεν είναι έγκυρο PDF.');const id=caseId+'/'+crypto.randomUUID()+'.pdf';if(demo)await local('files','readwrite',s=>s.put({id,blob:file}));else await api('/storage/v1/object/mc-documents/'+id,{method:'POST',body:new Blob([file],{type:'application/pdf'}),headers:{'Content-Type':'application/pdf'}});return {path:id,name:file.name};}
export async function fileURL(file){if(demo){const f=await local('files','readonly',s=>s.get(file.path));if(!f)throw Error('Δεν βρέθηκε το PDF σε αυτόν τον browser.');return URL.createObjectURL(f.blob);}const d=await api('/storage/v1/object/sign/mc-documents/'+file.path,{method:'POST',body:{expiresIn:60}});return base+'/storage/v1'+d.signedURL;}
export async function seed(){if(!demo)throw Error('Τα δείγματα επιτρέπονται μόνο στη δοκιμαστική λειτουργία.');const current=await load();if(current.cases.length||current.companies.length)throw Error('Τα δείγματα εισάγονται μόνο σε κενή δοκιμαστική βάση.');const companies=['Atlas Medical (demo)','Helix Supplies (demo)','Aegean Med (demo)'].map(name=>({id:crypto.randomUUID(),name,contact:'',email:'',notes:'Πλασματικά στοιχεία επίδειξης'}));for(const c of companies)await saveCompany(c);
 const ago=n=>{const d=new Date();d.setDate(d.getDate()-n);return d.toLocaleDateString('sv-SE');};
 for(let i=0;i<5;i++){const costs=i===0?[400000,350000,250000]:[180000+i*21000,90000+i*12000],total=costs.reduce((a,b)=>a+b),recognized=Math.round(total*.6),proposals=allocate(costs,total-recognized);const c={id:crypto.randomUUID(),version:0,code:'DEMO-'+(2401+i),patient:'Δοκιμαστικός ασθενής '+(i+1),doctor:['Ιατρός Α (demo)','Ιατρός Β (demo)'][i%2],incidentDate:ago(53-i*7),date:ago(50-i*7),type:'Plafond',total,recognized,notes:'Αποκλειστικά πλασματικά δεδομένα για δοκιμή.',closedReason:'',decision:null,lines:costs.map((cost,j)=>({id:crypto.randomUUID(),companyId:companies[j].id,cost,proposed:proposals[j],requested:proposals[j],received:i===2||i===1&&j===0?proposals[j]:0,stage:i===2||i===1&&j===0?'Παραλήφθηκε':i===4?'Προς αίτηση':'Ζητήθηκε',requestDate:i===4?'':ago(45-i*7),receiveDate:i===2||i===1&&j===0?ago(3):'',creditNumber:i===2||i===1&&j===0?'DEMO-Π-'+i+j:'',notes:'',credit:null}))};await saveCase(c);}}
