import {config} from '../config.js';
import {validate} from './domain.js';
let session=JSON.parse(sessionStorage.getItem('medicredit-session')||'null'),refreshing;
const recoveryParams=new URLSearchParams(typeof location==='undefined'?'':location.hash.slice(1));
let recovery=recoveryParams.get('type')==='recovery'&&!!recoveryParams.get('access_token');
if(recovery){session={access_token:recoveryParams.get('access_token'),refresh_token:recoveryParams.get('refresh_token'),expires_in:Number(recoveryParams.get('expires_in')||3600),expires_at:Date.now()+Number(recoveryParams.get('expires_in')||3600)*1000};sessionStorage.setItem('medicredit-session',JSON.stringify(session));}
const base=config.supabaseUrl.replace(/\/$/,'');
async function auth(path,body){const r=await fetch(base+'/auth/v1/'+path,{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.msg||d.error_description||d.message||'Αποτυχία σύνδεσης.');session={...d,expires_at:Date.now()+d.expires_in*1000};sessionStorage.setItem('medicredit-session',JSON.stringify(session));return d;}
async function token(){if(!session)throw Error('Απαιτείται σύνδεση.');if(Date.now()>session.expires_at-60000){refreshing??=auth('token?grant_type=refresh_token',{refresh_token:session.refresh_token}).finally(()=>refreshing=null);await refreshing;}return session.access_token;}
async function api(path,{method='GET',body,headers={}}={}){const r=await fetch(base+path,{method,headers:{apikey:config.publishableKey,Authorization:'Bearer '+await token(),...(body instanceof Blob?{}:{'Content-Type':'application/json'}),...headers},body:body===undefined?undefined:body instanceof Blob?body:JSON.stringify(body)});if(!r.ok){let d;try{d=await r.json();}catch{}throw Error(d?.message||d?.msg||d?.error||`Αποτυχία (${r.status}). Ελέγξτε σύνδεση και δικαιώματα.`);}const text=await r.text();return text?JSON.parse(text):null;}
async function allRemote(table){let rows=[],page;const fields=table==='mc_cases'?'id,payload,version':'*';do{page=await api(`/rest/v1/${table}?select=${fields}&order=id&limit=500&offset=${rows.length}`);rows.push(...page);}while(page.length===500);return rows;}
export const signedIn=()=>!!session;
export const recovering=()=>recovery;
export async function login(email,password){if(!base||!config.publishableKey)throw Error('Συμπληρώστε το config.js για το νέο Supabase project.');await auth('token?grant_type=password',{email,password});}
export async function updatePassword(password){if(password.length<8)throw Error('Ο νέος κωδικός πρέπει να έχει τουλάχιστον 8 χαρακτήρες.');const r=await fetch(base+'/auth/v1/user',{method:'PUT',headers:{apikey:config.publishableKey,Authorization:'Bearer '+await token(),'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw Error(d.msg||d.message||'Δεν ήταν δυνατή η αλλαγή κωδικού.');recovery=false;if(typeof history!=='undefined')history.replaceState(null,'',location.pathname+location.search);return d;}
export async function logout(){try{await api('/auth/v1/logout',{method:'POST'});}finally{session=null;sessionStorage.removeItem('medicredit-session');}}
const normalizeCase=c=>({...c,incidentDate:c.incidentDate||c.date});
export async function load(){const members=await api('/rest/v1/mc_members?select=user_id&active=eq.true');if(!members.length)throw Error('Ο λογαριασμός δεν έχει ενεργή πρόσβαση στο Τμήμα Προμηθειών. Επικοινωνήστε με τον διαχειριστή.');const [rows,companies]=await Promise.all([allRemote('mc_cases'),allRemote('mc_companies')]);return {cases:rows.map(r=>normalizeCase({...r.payload,id:r.id,version:r.version})),companies};}
export async function saveCase(c){const errors=validate(c);if(errors.length)throw Error(errors.join('\n'));const row=await api('/rest/v1/rpc/mc_save_case',{method:'POST',body:{p_case:c,p_version:c.version||0}});return {...row.payload,id:row.id,version:row.version};}
export async function saveCompany(c){if(!c.name.trim())throw Error('Απαιτείται επωνυμία.');const body={id:c.id,name:c.name,contact:c.contact,email:c.email,notes:c.notes};await api('/rest/v1/mc_companies?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body});}
export async function upload(file,caseId){if(file.size>10*1024*1024)throw Error('Το PDF πρέπει να είναι έως 10 MB.');if(new TextDecoder().decode(await file.slice(0,5).arrayBuffer())!=='%PDF-')throw Error('Το αρχείο δεν είναι έγκυρο PDF.');const id=caseId+'/'+crypto.randomUUID()+'.pdf';await api('/storage/v1/object/mc-documents/'+id,{method:'POST',body:new Blob([file],{type:'application/pdf'}),headers:{'Content-Type':'application/pdf'}});return {path:id,name:file.name};}
export async function fileURL(file){const d=await api('/storage/v1/object/sign/mc-documents/'+file.path,{method:'POST',body:{expiresIn:60}});return base+'/storage/v1'+d.signedURL;}
